services:
  db:
    image: mysql
    container_name: bookmarkDb
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: dev
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
